var keresztnev = 'Pisti';
var a = 2;
console.log(keresztnev);
var vezeteknev = 'Kis';
console.log(vezeteknev);
var kor = 32;
console.log(kor);
var nagykoru = false;
console.log(nagykoru);
var magassag;
console.log(magassag);